baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'netcrave'

[module]
  [[Module.mounts]]
    source = "static/img"
    target = "static/img"
  [[Module.mounts]]
    source = "static/dl"
    target = "static/dl"