module:
  hugoVersion:
    min: "0.84.0"
  mounts:
  - source: content
    target: content
  - source: static
    target: static
  - source: layouts
    target: layouts
  - source: data
    target: data
  - source: assets
    target: assets
  - source: i18n
    target: i18n
  - source: archetypes
    target: archetypes
  - source: 'node_modules/font-awesome/scss'
    target: 'assets/netcrave/css/font-awesome'
  - source: 'node_modules/font-awesome/fonts'
    target: 'static/font-awesome/fonts'
  - source: 'node_modules/font-awesome/fonts'
    target: 'static/font-awesome'
  - source: 'node_modules/sf-font'
    target: 'static/sf-font'

